# src/handlers/__init__.py
from __future__ import annotations

from typing import Protocol


class ConnectionLike(Protocol):
    """Минимальный интерфейс"""

    def recv_line(self) -> str: ...
    def send_line(self, data: str) -> None: ...
    def recv_bytes(self, n: int) -> bytes: ...
    def send_bytes(self, data: bytes) -> None: ...
    def close(self) -> None: ...
